export const FETCH_USER_ENTRY_LIST_SUCCESS = "FETCH_USER_ENTRY_LIST_SUCCESS";
export const FETCH_USER_ENTRY_LIST_REQUEST = "FETCH_USER_ENTRY_LIST_REQUEST";
export const FETCH_USER_ENTRY_LIST_FAILURE = "FETCH_USER_ENTRY_LIST_FAILURE";

export const FETCH_USER_ENTRY_BY_NAME_SUCCESS =
  "FETCH_USER_ENTRY_BY_NAME_SUCCESS";
export const FETCH_USER_ENTRY_BY_NAME_REQUEST =
  "FETCH_USER_ENTRY_BY_NAME_REQUEST";
export const FETCH_USER_ENTRY_BY_NAME_FAILURE =
  "FETCH_USER_ENTRY_BY_NAME_FAILURE";
export const POST_USER_ENTRY_SUCCESS = "POST_USER_ENTRY_SUCCESS";
export const POST_USER_ENTRY_REQUEST = "POST_USER_ENTRY_REQUEST";
export const POST_USER_ENTRY_FAILURE = "POST_USER_ENTRY_FAILURE";

export const FETCH_SCORE_TABLE_SUCCESS = "FETCH_SCORE_TABLE_SUCCESS";
export const FETCH_SCORE_TABLE_REQUEST = "FETCH_SCORE_TABLE_REQUEST";
export const FETCH_SCORE_TABLE_FAILURE = "FETCH_SCORE_TABLE_FAILURE";
